#!/bin/bash
SRCPATH=./test
MODEL=gpt35

function _total() {
    # local result=`find $SRCPATH/*/$1 -type f -name "rnl.txt" | sort | xargs nl -bt | grep -v -e "Example$" | awk 'NF' | nl | tail -1 | awk '{print $1} END {if (NR == 0) print 0}'`
    local result=`find $SRCPATH/*/$1 -type f -name "rnl.txt" | sort | xargs grep -v -e "Example$" -e "\:$" -e "^$" | awk 'NF' | nl | tail -1 | awk '{print $1} END {if (NR == 0) print 0}'`
    echo $result
}

function _trans() {
    local postcount=`grep -r 'ensures' $SRCPATH/*/$1/jml/*.jml | grep -v 'Lexer:' | grep -v 'Parser:' | awk 'END {print NR}'`
    local precount=`grep -r 'requires' $SRCPATH/*/$1/jml/*.jml | grep -v 'Lexer:' | grep -v 'Parser:' | awk 'END {print NR}'`
    echo $(($postcount+$precount))

}

function _derive() {
    local failed=`find ./test/*/$1/tmp -type f -name "*.mr" | xargs grep "Failed" | awk 'END {print NR}'`
    local empty=`find ./test/*/$1/tmp -type f -name "*.mr" -empty | awk 'END {print NR}'`
    local incomplete=`find ./test/*/$1/tmp -type f -name "*.mr" | xargs grep -F '\' | awk 'END {print NR}'`
    local total=`find ./test/*/$1/tmp -type f -name "*.mr" | nl | tail -1 | awk '{print $1} END {if (NR == 0) print 0}'`
    echo $(($total-$failed-$empty-$incomplete))
}

function _parse() {
    local parsing_error=`grep 'Parser: parse error' ./results/"$1"log  | nl | tail -1 | awk '{print $1} END {if (NR == 0) print 0}'`
    local sinotfounderror=`grep 'SI not found error' ./results/"$1"log  | nl | tail -1 | awk '{print $1} END {if (NR == 0) print 0}'`	
    local semanticerror=`grep 'Semantic error' ./results/"$1"log  | nl | tail -1 | awk '{print $1} END {if (NR == 0) print 0}'`
    local sianalysiserror=`grep 'Internal error' ./results/"$1"log  | nl | tail -1 | awk '{print $1} END {if (NR == 0) print 0}'`
    echo $(($parsing_error+$sinotfounderror+$semanticerror+$sianalysiserror))
}

date=20250117

echo '' > results/$date/starchat_report.txt
echo '' > results/$date/gpt4_report.txt
echo '' > results/$date/gpt35_report.txt

for entry in `find ./test/*/starchat/jml -type f -name "*.jml" | sort`
do
    echo $entry >> results/$date/starchat_report.txt
done

for entry in `find ./test/*/gpt4/jml -type f -name "*.jml" | sort`
do
    echo $entry >> results/$date/gpt4_report.txt
done

for entry in `find ./test/*/gpt35/jml -type f -name "*.jml" | sort`
do
    echo $entry >> results/$date/gpt35_report.txt
done



gpt35=`bc -l <<< "($(_trans "gpt35") / $(_total "gpt35")) * 100"`
gpt4=`bc -l <<< "($(_trans "gpt4") / $(_total "gpt4")) * 100"`
starchat=`bc -l <<< "($(_trans "starchat") / $(_total "starchat")) * 100"`
echo $(_trans "gpt35") $(_total "gpt35") $gpt35 $(_derive "gpt35") $(_parse "gpt35")
echo $(_trans "gpt4") $(_total "gpt4") $gpt4 $(_derive "gpt4") $(_parse "gpt4")	
echo $(_trans "starchat") $(_total "starchat") $starchat $(_derive "starchat") $(_parse "starchat")


# postcount=`grep -r 'ensures' $SRCPATH/*/gpt35/jml/*.jml | grep -v 'Lexer:' | grep -v 'Parser:' | awk 'END {print NR}'`
# precount=`grep -r 'requires' $SRCPATH/*/gpt35/jml/*.jml | grep -v 'Lexer:' | grep -v 'Parser:' | awk 'END {print NR}'`
# let gpt35_transok=$(($postcount+$precount))

# grep -rl 'Failed' $SRCPATH/*/tmp/*.mr > ./tmp/p1failed
# grep -rl '\\' $SRCPATH/*/tmp/*.mr >> ./tmp/p1failed
# find $SRCPATH/ -name "*.mr" -type f -empty >> ./tmp/p1failed
# p1failed=`uniq ./tmp/p1failed | awk 'END {print NR}'`
# let p1ok=$(($total-$p1failed))
# p1percent=`bc -l <<<"($p1ok / $total) * 100"`


# p2correct_post=`grep -r '//@ ensures' ./fmcheck/input/hart/*/Solution.java | awk 'END {print NR}'`
# p2correct_pre=`grep -r '//@ requires' ./fmcheck/input/hart/*/Solution.java | awk 'END {print NR}'`
# p2wrong_post=`grep -r '// ensures' ./fmcheck/input/hart/*/Solution.java | awk 'END {print NR}'`
# p2wrong_pre=`grep -r '// requires' ./fmcheck/input/hart/*/Solution.java | awk 'END {print NR}'`
# let p2correct=$(($p2correct_post+$p2correct_pre))
# let p2total=$(($p2correct_post+$p2correct_pre+$p2wrong_post+$p2wrong_pre))


# llmtotal=`grep -E '^\/\/\s?[^#]+' ./fmcheck/input/gpt35/*/Solution.java | grep -v '#' | wc -l`
# llmp2correct_post=`grep -r '//@ ensures' ./fmcheck/input/gpt35/*/Solution.java | awk 'END {print NR}'`
# llmp2correct_pre=`grep -r '//@ requires' ./fmcheck/input/gpt35/*/Solution.java | awk 'END {print NR}'`
# llmp2wrong=`grep -r '//' ./fmcheck/input/gpt35/*/Solution.java | grep -v '#' | grep -v '@' | awk 'END {print NR}'`
# let llmcorrect=$(($llmp2correct_post+$llmp2correct_pre))

# p2percent=`bc -l <<< "($p2correct / $total) * 100"`
# echo 'Total sentence processed: ' $total
# echo 'P1 failed cases: ' $p1failed
# echo 'translation success cases: ' $transok
# echo 'P1 successful rate: ' $p1percent
# echo 'translation successful rate out of all sentences: ' `bc -l <<< "($transok / $total) * 100"`
# echo 'translation successful rate out of all MRs: ' `bc -l <<< "($transok / $p1ok) * 100"`
# echo 'translation correct rate(regarding syntax and semantic): ' `bc -l <<< "($p2correct/$total) * 100"` "$p2correct out of $total"
# echo 'LLM correct rate(regarding syntax and semantic):' `bc -l <<< "($llmcorrect/$llmtotal) * 100"` "$llmcorrect out of $llmtotal"
