#!/bin/bash

ROOT=`pwd`
# provide the path to the python virtual environment
PYVENV=/home/chrissleong/venv/py3
# provide the path to ccg2lambda
NLP=/home/chrissleong/release/ccg2lambda-master

# path to standard semantic interpretation library
STD_SI=./src/c/lib/std_si_2022.yml
TMP=./tmp

PYCMD=$PYVENV/bin/python

# create a tmp directory for intermediate files
mkdir -p $TMP
rm -rf $TMP/*

filename="$(basename $1)"
tmpname="$(basename -s .java $1)"

# preprocessing
$PYCMD ./src/python/preprocessor.py $1 $STD_SI $TMP

raw_conditions=$tmpname.conditions.yml
prog_si=$tmpname.si.yml

# check files generated
if [[ -f "$TMP/$tmpname.conditions.yml" && -f "$TMP/$tmpname.si.yml" ]]; then

    # parsing the conditions.yml file
    $PYCMD ./src/python/pipeline.py $NLP $TMP/$raw_conditions $PYCMD $STD_SI
else
    echo "======================================================================================"
    [ -f "$TMP/$tmpname.conditions.yml" ] && echo "Please provide the SI file at $TMP/$tmpname.si.yml"
    [ -f "$TMP/$tmpname.si.yml" ] && echo "Please provide the MR file at $TMP/$tmpname.conditions.yml"
    echo "======================================================================================"
fi




