package g0501_0600.s0504_base_7;

// #Easy #Math #2022_07_24_Time_0_ms_(100.00%)_Space_39.4_MB_(98.67%)

public class Solution {
//@ requires(*The integer parameter `num` is less than or equal to 10000000 and is greater than or equal to -10000000.*);
//@ requires(**);
//@ requires(*Example #19*);
//@ requires(*Software specification: 2415\. Longest Substring Without Repeating Characters and Unique Digits*);
//@ requires(*Hard*);
//@ requires(*Given a string `s`, return _the length of the longest substring without repeating characters and unique digits_.*);
//@ requires(***Example 1:***);
//@ requires(**);
//@ requires(***Input:** s =  "abcabcbb "*);
//@ requires(***Output:** 3*);
//@ requires(***Explanation:** The longest substring is  "abc ", with the length of 3.*);
//@ requires(**);
//@ requires(***Example 2:***);
//@ requires(**);
//@ requires(***Input:** s =  "bbbbb "*);
//@ requires(***Output:** 1*);
//@ requires(***Explanation:** The longest substring is  "b ", with the length of 1. Note that the answer must be a substring,  "bb " is not a substring.*);
//@ requires(**);
//@ requires(***Example 3:***);
//@ requires(**);
//@ requires(***Input:** s =  "pwwkew "*);
//@ requires(***Output:** 3*);
//@ requires(***Explanation:** The longest substring is  "wke ", with the length of 3. Note that the answer must be a substring,  "ew " is not a substring.*);
//@ requires(**);
//@ requires(***Constraints:***);
//@ requires(**);
//@ requires(**   `1 <= s.length <= 5 * 104`*);
//@ requires(**   `s` consists of English letters, digits, and symbols.*);
//@ requires(**);
//@ requires(*Method signature: public int lengthOfLongestSubstring(String s)*);
//@ requires(*Method behavioural specifications:*);
//@ requires(*The length of the string parameter `s` is less than or equal to 50000 and is greater than or equal to 1.*);
//@ requires(*The string parameter `s` consists of only English letters, digits, and symbols.*);
//@ requires(**);
//@ requires(*Example #20*);
//@ requires(*Software specification: 2416\. Longest Substring Without Repeating Characters and Unique Digits II*);
//@ requires(*Hard*);
//@ requires(*Given a string `s`, return _the length of the longest substring without repeating characters and unique digits_.*);
//@ requires(***Example 1:***);
//@ requires(**);
//@ requires(***Input:** s =  "abcabcbb "*);
//@ requires(***Output:** 3*);
//@ requires(***Explanation:** The longest substring is  "abc ", with the length of 3.*);
//@ requires(**);
//@ requires(***Example 2:***);
//@ requires(**);
//@ requires(***Input:** s =  "bbbbb "*);
//@ requires(***Output:** 1*);
//@ requires(***Explanation:** The longest substring is  "b ", with the length of 1. Note that the answer must be a substring,  "bb " is not a substring.*);
//@ requires(**);
//@ requires(***Example 3:***);
//@ requires(**);
//@ requires(***Input:** s =  "pwwkew "*);
//@ requires(***Output:** 3*);
//@ requires(***Explanation:** The longest substring is  "wke ", with the length of 3. Note that the answer must be a substring,  "ew " is not a substring.*);
//@ requires(**);
//@ requires(***Constraints:***);
//@ requires(**);
//@ requires(**   `1 <= s.length <= 5 * 104`*);
//@ requires(**   `s` consists of English letters, digits, and symbols.*);
//@ requires(**);
//@ requires(*Method signature: public int lengthOfLongestSubstring(String s)*);
//@ requires(*Method behavioural specifications:*);
//@ requires(*The length of the string parameter `s` is less than or equal to 50000 and is greater than or equal to 1.*);
//@ requires(*The string parameter `s` consists of only English letters, digits, and symbols.*);
//@ ensures(*The string result is a valid base 7 representation of the integer parameter `num`.*);
//@ ensures(*The string result does not contain leading zeros, except for the number zero itself.*);
//@ ensures(*If the integer parameter `num` is equal to 100, the string result is equal to "202".*);
//@ ensures(*If the integer parameter `num` is equal to -7, the string result is equal to "-10".*);
//@ ensures(*The integer result is greater than or equal to 0 and is less than or equal to the length of the string parameter `s`.*);
//@ ensures(*If the string parameter `s` is equal to "abcabcbb", the integer result is equal to 3.*);
//@ ensures(*If the string parameter `s` is equal to "bbbbb", the integer result is equal to 1.*);
//@ ensures(*If the string parameter `s` is equal to "pwwkew", the integer result is equal to 3.*);
//@ ensures(*The integer result is greater than or equal to 0 and is less than or equal to the length of the string parameter `s`.*);
//@ ensures(*If the string parameter `s` is equal to "abcabcbb", the integer result is equal to 3.*);
//@ ensures(*If the string parameter `s` is equal to "bbbbb", the integer result is equal to 1.*);
//@ ensures(*If the string parameter `s` is equal to "pwwkew", the integer result is equal to*);
    public String convertToBase7(int num) {
        return Integer.toString(num, 7);
    }
}